vlaue = {u'origin': False, u'message_follower_ids': False, u'via': u'M',
         u'order_line': [[0, False, {u'procurement_ids': [],
                                     u'qty_delivered': 0,
                                     u'product_id': 2,
                                     u'product_uom': 1,
                                     u'sequence': 10,
                                     u'customer_lead': 0,
                                     u'price_unit': 0.1,
                                     u'product_uom_qty': 1,
                                     u'discount': 0,
                                     u'state': u'draft',
                                     u'qty_delivered_updateable': True,
                                     u'analytic_tag_ids': [],
                                     u'invoice_status': u'no',
                                     u'tax_id': [
                                         [6, False, [1]]],
                                     u'layout_category_id': False,
                                     u'name': u'[AGNTPORT] Agente portuario\nAgente portuario123'}],
                         [0, False, {u'procurement_ids': [],
                                     u'qty_delivered': 0,
                                     u'product_id': 7,
                                     u'product_uom': 1,
                                     u'sequence': 11,
                                     u'customer_lead': 0,
                                     u'price_unit': 0.1,
                                     u'product_uom_qty': 1,
                                     u'discount': 0,
                                     u'state': u'draft',
                                     u'qty_delivered_updateable': True,
                                     u'analytic_tag_ids': [],
                                     u'invoice_status': u'no',
                                     u'tax_id': [
                                         [6, False, [1]]],
                                     u'layout_category_id': False,
                                     u'name': u'[RESGUARDO] Servicio de resguardo\nServicio de resguardo'}]],
         u'modalidad_pago_id': False,
         u'tipo_contenedor_id': 1,
         u'client_order_ref': False,
         u'date_order': u'2018-05-29 11:20:37',
         u'partner_id': 7,
         u'message_ids': False,
         u'user_id': 1,
         u'actividad': u'E',
         u'company_id': 1,
         u'note': False,
         u'pricelist_id': 1,
         u'project_id': False,
         u'validity_date': u'2018-05-29',
         u'payment_term_id': 3,
         u'partner_invoice_id': 7,
         u'modalidad': u'FCL',
         u'fiscal_position_id': False,
         u'valor_tipo_cambio': 3.2720000000000002,
         u'partner_shipping_id': 7,
         u'team_id': 1}
