# -*- coding: utf-8 -*-
{
    'name': "biosis_cubso",

    'summary': """
        El Catálogo Único de Bienes, Servicios y Obras - CUBSO """,

    'description': """
        Data agregada por Biosis
    """,

    'author': "BIOSIS",
    'website': "http://www.yourcompany.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/master/odoo/addons/base/module/module_data.xml
    # for the full list
    'category': 'Uncategorized',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': ['base','account'],

    # always loaded
    'data': [
        'data/anexo3_tablas.xml',
        'data/cubso_1.xml',
        'data/cubso_2.xml',
        'data/cubso_3.xml',
        'data/cubso_4.xml',
        'data/cubso_5.xml',
        'data/cubso_6.xml',
        'data/cubso_7.xml',
        'data/cubso_8.xml',
        'data/cubso_9.xml',
        'data/cubso_10.xml',
        'data/cubso_11.xml',
        'data/cubso_12.xml',
        'data/cubso_13.xml',
        'data/cubso_14.xml',
        'data/cubso_15.xml',
        'data/cubso_16.xml',
        'data/cubso_17.xml',
        'data/cubso_18.xml',
        'data/cubso_19.xml',
        'data/cubso_20.xml',
        'data/cubso_21.xml',
        'data/cubso_22.xml',
        'data/cubso_23.xml',
        'data/cubso_24.xml',
        'data/cubso_25.xml',
        'data/cubso_26.xml',
        'data/cubso_27.xml',
        'data/cubso_28.xml',
        'data/cubso_29.xml',
        'data/cubso_30.xml',
        'data/cubso_31.xml',
        'data/cubso_32.xml',
        'data/cubso_33.xml',
        'data/cubso_34.xml',
        'data/cubso_35.xml',
        'data/cubso_36.xml',
        'data/cubso_37.xml',
        'data/cubso_38.xml',
        'data/cubso_39.xml',
        'data/cubso_40.xml',
        'data/cubso_41.xml',
        'data/cubso_42.xml',
        'data/cubso_43.xml',
        'data/cubso_44.xml',
        'data/cubso_45.xml',
        'data/cubso_46.xml',
        'data/cubso_47.xml',
        'data/cubso_48.xml',
        'data/cubso_49.xml',
        'data/cubso_50.xml',
        'data/cubso_51.xml',
        'data/cubso_52.xml',
        'data/cubso_53.xml',
        'data/cubso_54.xml',
        'data/cubso_55.xml',
        'data/cubso_56.xml',
        'data/cubso_57.xml',
        'data/cubso_58.xml',
        'data/cubso_59.xml',
        'data/cubso_60.xml',
        'data/cubso_61.xml',
        'data/cubso_62.xml',
        'data/cubso_63.xml',
        'data/cubso_64.xml',
        'data/cubso_65.xml',
        'data/cubso_66.xml',
        'data/cubso_67.xml',
        'data/cubso_68.xml',
        'data/cubso_69.xml',
        'data/cubso_70.xml',
        'data/cubso_71.xml',
        'data/cubso_72.xml',
        'data/cubso_73.xml',
        'data/cubso_74.xml',
        'data/cubso_75.xml',
        'data/cubso_76.xml',
        'data/cubso_77.xml',
        'data/cubso_78.xml',
        'data/cubso_79.xml',
        'data/cubso_80.xml',
        'data/cubso_81.xml',
        'data/cubso_82.xml',
        'data/cubso_83.xml',
        'data/cubso_84.xml',
        'data/cubso_85.xml',
        'data/cubso_86.xml',
        'data/cubso_87.xml',
        'data/cubso_88.xml',
        'data/cubso_89.xml',
        'data/cubso_90.xml',
        'data/cubso_91.xml',
        'data/cubso_92.xml',
        'data/cubso_93.xml',
        'data/cubso_94.xml',
        'data/cubso_95.xml',
        'data/cubso_96.xml',
        'data/cubso_97.xml',
        'data/cubso_98.xml',
        'data/cubso_99.xml',
        'data/cubso_100.xml',
        'data/cubso_101.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        #'demo/demo.xml',
    ],
}